{% set name = "nbresuse" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ec9ed2b3df56d8198c9384ac80af1e370b3991ba4e405f16f7629bb9239fac4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - notebook
    - psutil
    - python >=3.5

test:
  imports:
    - nbresuse

about:
  home: https://github.com/yuvipanda/nbresuse
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Notebook Extension for monitoring Resource Usage
  dev_url: https://github.com/yuvipanda/nbresuse

extra:
  recipe-maintainers:
    - krinsman
    - jtpio
